/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import CorreioEletronico.Correio;
import CorreioEletronico.CorreioDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Marti
 */
public class CaixaEntrada extends javax.swing.JFrame {

    /**
     * Creates new form CaixaEntrada
     */
    public CaixaEntrada() {
        initComponents();DefaultTableModel modelo = (DefaultTableModel) jtaMensagens.getModel();
        jtaMensagens.setRowSorter(new TableRowSorter(modelo));
        this.setLocationRelativeTo(null);
        //readJTable();
        
    }
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jtaMensagens.getModel();
        modelo.setNumRows(0);
        CorreioDAO pdao = new CorreioDAO();
        int i = 0;
        
        for (Correio p : pdao.read()) {
            i += 1;
            modelo.addRow(new Object[]{
                //p.getId_mensagem(),
                p.getRemetente(),
                p.getDestinatario(),
                p.getAssunto(),
                p.getMensagem(),
                p.getData(),
            });

        }

    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMensagem = new javax.swing.JTextField();
        txtDestinatario = new javax.swing.JTextField();
        txtdata = new javax.swing.JTextField();
        txtAssunto = new javax.swing.JTextField();
        txtRemetente = new javax.swing.JTextField();
        btn_att = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMensagens = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(7, 101, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa de Entrada");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, -1));

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel2.setText("DATA:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jLabel3.setText("DESTINÁTARIO: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 20));

        jLabel4.setText("REMETENTE: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel5.setText("ASSUNTO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel6.setText("MENSAGEM: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        txtMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensagemActionPerformed(evt);
            }
        });
        jPanel2.add(txtMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 120, 60));

        txtDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinatarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, -1));

        txtdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdataActionPerformed(evt);
            }
        });
        jPanel2.add(txtdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, -1));

        txtAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssuntoActionPerformed(evt);
            }
        });
        jPanel2.add(txtAssunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 120, 60));

        txtRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRemetenteActionPerformed(evt);
            }
        });
        jPanel2.add(txtRemetente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, -1));

        btn_att.setText("ATUALIZAR");
        btn_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attActionPerformed(evt);
            }
        });
        jPanel2.add(btn_att, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtaMensagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESTINATARIO", "REMETENTE", "ASSUNTO", "MENSAGEM", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtaMensagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtaMensagensMouseClicked(evt);
            }
        });
        jtaMensagens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaMensagensKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtaMensagens);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Correio p = new Correio();
        
        CorreioDAO control = new CorreioDAO();
        
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"DESEJA REALMENTE EXCLUIR?");
        if(resposta == JOptionPane.YES_OPTION);
           p.setAssunto(txtAssunto.getText());
           control.delete(p);
           ((DefaultTableModel) jtaMensagens.getModel()).removeRow(jtaMensagens.getSelectedRow());
           txtAssunto.setText("");
           txtDestinatario.setText("");
           txtMensagem.setText("");
           txtdata.setText("");
           txtRemetente.setText("");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jtaMensagensKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaMensagensKeyReleased
        // TODO add your handling code here:
        /*
        if (jtaMensagens.getSelectedRow() != -1) {

            txtDesc.setText(jtaMensagens.getValueAt(jtaMensagens.getSelectedRow(), 1).toString());
            txtQtd.setText(jtaMensagens.getValueAt(jtaMensagens.getSelectedRow(), 2).toString());
            txtPreco.setText(jtaMensagens.g

            }
            */
    }//GEN-LAST:event_jtaMensagensKeyReleased

    private void jtaMensagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtaMensagensMouseClicked
      
      int linha = jtaMensagens.getSelectedRow();
      
      txtRemetente.setText(jtaMensagens.getValueAt(linha, 0).toString());
      txtDestinatario.setText(jtaMensagens.getValueAt(linha, 1).toString());
      txtAssunto.setText(jtaMensagens.getValueAt(linha, 2).toString());
      txtMensagem.setText(jtaMensagens.getValueAt(linha, 3).toString());
      txtdata.setText(jtaMensagens.getValueAt(linha, 4).toString());
      
    }//GEN-LAST:event_jtaMensagensMouseClicked

    private void txtMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensagemActionPerformed

    private void txtDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinatarioActionPerformed

    private void txtdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdataActionPerformed

    private void txtAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssuntoActionPerformed

    private void txtRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemetenteActionPerformed

    private void btn_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attActionPerformed
        readJTable();
    }//GEN-LAST:event_btn_attActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaixaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaixaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaixaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaixaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaixaEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btn_att;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtaMensagens;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtMensagem;
    private javax.swing.JTextField txtRemetente;
    private javax.swing.JTextField txtdata;
    // End of variables declaration//GEN-END:variables
}
