package Telas;

import CorreioEletronico.Correio;
import Socket.ClienteDeChat;
import com.sun.javafx.collections.SourceAdapterChange;
import java.awt.HeadlessException;
import java.io.IOException;
import java.io.PrintStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.text.DefaultCaret;


/**
 *
 * @author Lucas
 */
public class TelaChat extends javax.swing.JFrame {

    ClienteDeChat cliente;
    public static String online;
    
    /**
     * Creates new form TelaChat
     */
    public TelaChat() {
        initComponents();
        jtfMsg.grabFocus();
        getRootPane().setDefaultButton(jbEnviarMsg);
        this.setLocationRelativeTo(null);
        DefaultCaret caret = (DefaultCaret) jtaMsgs.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }

    /**
     * Cria o socket de conexão com o servidor e inicia a thread que fica "escutando" por novas mensagens.
     */
    public void conecta() {
        
        
        this.setTitle("Chat Global - " + TelaLogin.nomeUsuario);
        jtaMsgs.setText(TelaLogin.nomeUsuario + " entrou no chat");
        try {
            // Para se conectar a algum servidor, basta se criar um
            // objeto da classe Socket. O primeiro parâmetro é o IP ou
            // o endereço da máquina a qual se quer conectar e o
            // segundo parâmetro é a porta da aplicação. Neste caso,
            // utiliza-se o IP da máquina local (127.0.0.1) e a porta
            // da aplicação ServidorDeChat. Nada impede a mudança
            // desses valores, tentando estabelecer uma conexão com
            // outras portas em outras máquinas.
            Socket conexao = new Socket("127.0.0.1", 3333);
            this.cliente = new ClienteDeChat(conexao);
            // Uma vez estabelecida a comunicação, deve-se obter os
            // objetos que permitem controlar o fluxo de comunicação.
            PrintStream saida = new PrintStream(conexao.getOutputStream());
            saida.println(TelaLogin.nomeUsuario);
            // Uma vez que tudo está pronto, antes de iniciar o loop
            // principal, executar a thread de recepção de mensagens.
            Thread t = this.cliente;
            t.start();
        } catch (IOException e) {
            // Caso ocorra alguma excessão de E/S, mostre qual foi.
            System.out.println("IOException: " + e);
        }
    }

    public TelaChat(ClienteDeChat cliente, JButton jButton1, JMenu jMenu1, JMenuBar jMenuBar1, JMenuItem jMenuItem1, JMenuItem jMenuItem2, JMenuItem jMenuItem3, JMenuItem jMenuItem4, JPanel jPanel1, JPanel jPanel3, JScrollPane jScrollPane1, JPopupMenu.Separator jSeparator1, JButton jbEnviarMsg, JTextField jtfMsg) throws HeadlessException {
        this.cliente = cliente;
        this.jButton1 = jButton1;
        this.jMenu1 = jMenu1;
        this.jMenuBar1 = jMenuBar1;
        this.jMenuItem1 = jMenuItem1;
        this.jMenuItem2 = jMenuItem2;
        this.jMenuItem3 = jMenuItem3;
        this.jMenuItem4 = jMenuItem4;
        this.jPanel1 = jPanel1;
        this.jPanel3 = jPanel3;
        this.jScrollPane1 = jScrollPane1;
        this.jSeparator1 = jSeparator1;
        this.jbEnviarMsg = jbEnviarMsg;
        this.jtfMsg = jtfMsg;
    }
    /**
     * Envia uma mensagem para o servidor, que será enviada aos outros clientes.
     * @param msg String com a mensagem digitada.
     * @throws IOException 
     */
    public void sendMsg(String msg) throws IOException {
        jtaMsgs.setText(jtaMsgs.getText() + "\nVocê disse > " + jtfMsg.getText());
        jtfMsg.setText("");
        PrintStream saida = new PrintStream(cliente.getConexao().getOutputStream());
        // Antes de enviar, verifica se a conexão não foi fechada.
        if (cliente.getDone()) {
            System.exit(0);
        }
        saida.println(msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbEnviarMsg = new javax.swing.JButton();
        jtfMsg = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMsgs = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(545, 365));
        setResizable(false);
        setSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jbEnviarMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/enviar.png"))); // NOI18N
        jbEnviarMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarMsgActionPerformed(evt);
            }
        });

        jtfMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jtfMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbEnviarMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEnviarMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 550, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtaMsgs.setEditable(false);
        jtaMsgs.setColumns(20);
        jtaMsgs.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        jtaMsgs.setForeground(new java.awt.Color(51, 51, 51));
        jtaMsgs.setRows(5);
        jtaMsgs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtaMsgs.setMargin(new java.awt.Insets(3, 3, 2, 2));
        jScrollPane1.setViewportView(jtaMsgs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 490, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 320));

        jMenu1.setText("Opções");

        jMenuItem1.setText("Ver amigos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Correio Eletrônico");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Caixa de Entrada");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbEnviarMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarMsgActionPerformed
        if (!"".equals(jtfMsg.getText())) {
            try {
                sendMsg(jtfMsg.getText());
            } catch (IOException ex) {
                Logger.getLogger(TelaChat.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jtfMsg.grabFocus();
        }
    }//GEN-LAST:event_jbEnviarMsgActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       CorreioEletronico telaCorreio= new CorreioEletronico(); 
       telaCorreio.setVisible(true);
       
   
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       CaixaEntrada telaCaixa= new CaixaEntrada(); 
       telaCaixa.setVisible(true);
       
    
      
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbEnviarMsg;
    public static javax.swing.JTextArea jtaMsgs;
    private javax.swing.JTextField jtfMsg;
    // End of variables declaration//GEN-END:variables
}
