package Telas;

import Uteis.MD5;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author jonsanto1
 */
public final class TelaLogin extends javax.swing.JFrame {

    public static Socket conexao;

    /**
     * Creates new form TelaCadastro
     */
    TelaCadastro cadastro = new TelaCadastro();
    public static String nomeUsuario;
    public static String email;

    public TelaLogin() {
        initComponents();
        this.setTitle("Tela de Login");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        jtfEmail.grabFocus();
        jlAlerta.setVisible(false);
        this.setResizable(false);
        getRootPane().setDefaultButton(jbLogar);
        conectaBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jlAlerta = new javax.swing.JLabel();
        jbLogar = new javax.swing.JButton();
        lbSingUP = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(621, 381));
        setMinimumSize(new java.awt.Dimension(615, 370));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(7, 101, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Chat-Mail");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 275, 410));

        jtfEmail.setToolTipText("");
        jtfEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 109, 109)));
        jtfEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 315, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Senha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 215, -1, -1));

        jpfSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 109, 109)));
        jPanel1.add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 315, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("E-mail");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 135, -1, -1));

        jlAlerta.setForeground(new java.awt.Color(255, 0, 0));
        jlAlerta.setText("Alertas");
        jPanel1.add(jlAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jbLogar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbLogar.setText("Logar");
        jbLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogarActionPerformed(evt);
            }
        });
        jPanel1.add(jbLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 98, 45));

        lbSingUP.setBackground(new java.awt.Color(102, 102, 102));
        lbSingUP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbSingUP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSingUP.setText("Sign Up");
        jPanel1.add(lbSingUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 315, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 630, 400));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Novo Cadastro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Limpa os campos do login e "foca" no campo email.
     */
    public void limpaCampos() {
        jtfEmail.setText("");
        jtfEmail.grabFocus();
        jpfSenha.setText("");
    }

    public void conectaBD() {
        try {
            // criando conexão com o servidor
            TelaLogin.conexao = new Socket("127.0.0.1", 4444);
        } catch (IOException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        cadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogarActionPerformed
        TelaChat chat = new TelaChat();
        String linha;
        email = jtfEmail.getText();

        if (!"".equals(jtfEmail.getText()) && jpfSenha.getPassword().length != 0) {
            PrintStream saida;
            try {
                BufferedReader entrada = new BufferedReader(new InputStreamReader(conexao.getInputStream()));
                MD5 md5 = new MD5();
                String senha = new String(jpfSenha.getPassword());
                // objetos que permitem controlar o fluxo de comunicação.
                saida = new PrintStream(conexao.getOutputStream());
                saida.println("login");
                saida.println(jtfEmail.getText());
                saida.println(md5.gerarMD5(senha));
                nomeUsuario = entrada.readLine();
                if (!"null".equals(nomeUsuario)) {                    
                    this.setVisible(false);
                    cadastro.setVisible(false);
                    chat.conecta();
                    chat.setVisible(true);
                    saida.close();
                } else {
                    limpaCampos();
                    jlAlerta.setText("Usuário ou senha inválidos.");
                    jlAlerta.setVisible(true);
                }
            } catch (IOException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jlAlerta.setText("Preencha todos os campos.");
            jlAlerta.setVisible(true);

            if ("".equals(jtfEmail.getText())) {
                jtfEmail.grabFocus();
            } else {
                jpfSenha.grabFocus();
            }
        }
    }//GEN-LAST:event_jbLogarActionPerformed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbLogar;
    private javax.swing.JLabel jlAlerta;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JLabel lbSingUP;
    // End of variables declaration//GEN-END:variables
}
